main: lab3b.py
	python lab3b.py
run:
	chmod u+x lab3b.py
	python lab3b.py
dist:
	rm -rf lab3b-704448696.tar.gz
	tar -zcf lab3b-704448696.tar.gz *.py Makefile README
clean:
	rm -rf *.py
	rm -rf lab3b_check.txt